using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Qimmah.Migrations
{
    /// <inheritdoc />
    public partial class localizationseeding : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_AspNetUsers_Languages_LanguageID",
                schema: "Users",
                table: "AspNetUsers");

           

            migrationBuilder.DropPrimaryKey(
                name: "PK_Languages",
                schema: "Users",
                table: "Languages");

            migrationBuilder.EnsureSchema(
                name: "Localization");

            migrationBuilder.RenameTable(
                name: "Languages",
                schema: "Users",
                newName: "Language",
                newSchema: "Localization");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Language",
                schema: "Localization",
                table: "Language",
                column: "ID");

            migrationBuilder.CreateTable(
                name: "Dictionary",
                schema: "Localization",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Dictionary", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "DictionaryLocalization",
                schema: "Localization",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false),
                    LanguageID = table.Column<int>(type: "int", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DictionaryLocalization", x => new { x.ID, x.LanguageID });
                    table.ForeignKey(
                        name: "FK_DictionaryLocalization_Dictionary_ID",
                        column: x => x.ID,
                        principalSchema: "Localization",
                        principalTable: "Dictionary",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_DictionaryLocalization_Language_LanguageID",
                        column: x => x.LanguageID,
                        principalSchema: "Localization",
                        principalTable: "Language",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CompanyDictionaryLocalization",
                schema: "Localization",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false),
                    LanguageID = table.Column<int>(type: "int", nullable: false),
                    TenantID = table.Column<long>(type: "bigint", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DictionaryLocalizationID = table.Column<int>(type: "int", nullable: true),
                    DictionaryLocalizationLanguageID = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CompanyDictionaryLocalization", x => new { x.ID, x.LanguageID });
                    table.ForeignKey(
                        name: "FK_CompanyDictionaryLocalization_DictionaryLocalization_DictionaryLocalizationID_DictionaryLocalizationLanguageID",
                        columns: x => new { x.DictionaryLocalizationID, x.DictionaryLocalizationLanguageID },
                        principalSchema: "Localization",
                        principalTable: "DictionaryLocalization",
                        principalColumns: new[] { "ID", "LanguageID" });
                    table.ForeignKey(
                        name: "FK_CompanyDictionaryLocalization_DictionaryLocalization_ID_LanguageID",
                        columns: x => new { x.ID, x.LanguageID },
                        principalSchema: "Localization",
                        principalTable: "DictionaryLocalization",
                        principalColumns: new[] { "ID", "LanguageID" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CompanyDictionaryLocalization_Dictionary_ID",
                        column: x => x.ID,
                        principalSchema: "Localization",
                        principalTable: "Dictionary",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CompanyDictionaryLocalization_Language_LanguageID",
                        column: x => x.LanguageID,
                        principalSchema: "Localization",
                        principalTable: "Language",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                schema: "Localization",
                table: "Dictionary",
                column: "ID",
                values: new object[]
                {
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31,
                    32,
                    33,
                    34,
                    35,
                    36,
                    37,
                    38,
                    39,
                    40,
                    41,
                    42,
                    43,
                    44,
                    45,
                    46,
                    47,
                    48,
                    49,
                    50,
                    51,
                    52,
                    53,
                    54,
                    55,
                    56,
                    57,
                    58,
                    59,
                    60,
                    61,
                    62,
                    63,
                    64,
                    65,
                    66,
                    67,
                    68,
                    69,
                    70,
                    71,
                    72,
                    73,
                    74,
                    75,
                    76,
                    77,
                    78,
                    79,
                    80,
                    81,
                    82,
                    83,
                    84,
                    85,
                    86,
                    87,
                    88,
                    89,
                    90,
                    91,
                    92,
                    93,
                    94,
                    95,
                    96,
                    97,
                    98,
                    99,
                    100,
                    101,
                    102,
                    103,
                    104,
                    105,
                    106,
                    107,
                    108,
                    109,
                    110,
                    111,
                    112,
                    113,
                    114,
                    115,
                    116,
                    117,
                    118,
                    119,
                    120,
                    121,
                    122,
                    123,
                    124,
                    125,
                    126,
                    127,
                    128,
                    129,
                    130,
                    131,
                    132,
                    133,
                    134,
                    135,
                    136,
                    137,
                    138,
                    139,
                    140,
                    141,
                    142,
                    143,
                    144,
                    145,
                    146,
                    147,
                    148,
                    149,
                    150,
                    151,
                    152,
                    153,
                    154,
                    155,
                    156,
                    157,
                    158,
                    159,
                    160,
                    161,
                    162,
                    163,
                    164,
                    165,
                    166,
                    167,
                    168,
                    169,
                    170,
                    171,
                    172,
                    173,
                    174,
                    175,
                    176,
                    177,
                    178,
                    179,
                    180,
                    181,
                    182,
                    183,
                    184,
                    185,
                    186,
                    187,
                    188,
                    189,
                    190,
                    191,
                    192,
                    193,
                    194,
                    195,
                    196,
                    197,
                    198,
                    199,
                    200,
                    201,
                    202,
                    203,
                    204,
                    205,
                    206,
                    207,
                    208,
                    209,
                    210,
                    211,
                    212,
                    213,
                    214,
                    215,
                    216,
                    217,
                    218,
                    219,
                    220,
                    221,
                    222,
                    223,
                    224,
                    225,
                    226,
                    227,
                    228,
                    229,
                    230,
                    231,
                    232,
                    233,
                    234,
                    235,
                    236,
                    237,
                    238,
                    239,
                    240,
                    241,
                    242,
                    243,
                    244,
                    245,
                    246,
                    247,
                    248,
                    249,
                    250,
                    251,
                    252,
                    253,
                    254,
                    255,
                    256,
                    257,
                    258,
                    259,
                    260,
                    261,
                    262,
                    263,
                    264,
                    265,
                    266,
                    267,
                    268,
                    269,
                    270,
                    271,
                    272,
                    273,
                    274,
                    275,
                    276,
                    277,
                    278,
                    279,
                    280,
                    281,
                    282,
                    283,
                    284,
                    285,
                    286,
                    287,
                    288,
                    289,
                    290,
                    291,
                    292,
                    293,
                    294,
                    295,
                    296,
                    297,
                    298,
                    299,
                    300,
                    301,
                    302,
                    303,
                    304,
                    305,
                    306,
                    307,
                    308,
                    309,
                    310,
                    311,
                    312,
                    313,
                    314,
                    315,
                    316,
                    317,
                    318,
                    319,
                    320,
                    321,
                    322,
                    323,
                    324,
                    325,
                    326,
                    327,
                    328,
                    329,
                    330,
                    331,
                    332,
                    333,
                    334,
                    335,
                    336,
                    337,
                    338,
                    339,
                    340,
                    341,
                    342,
                    343,
                    344,
                    345,
                    346,
                    347,
                    348,
                    349,
                    350,
                    351,
                    352,
                    353,
                    354,
                    355,
                    356,
                    357,
                    358,
                    359,
                    360,
                    361,
                    362,
                    363,
                    364,
                    365,
                    366,
                    367,
                    368,
                    369,
                    370,
                    371,
                    372,
                    373,
                    374,
                    375,
                    376,
                    377,
                    378,
                    379,
                    380,
                    381,
                    382,
                    383,
                    384,
                    385,
                    386,
                    387,
                    388,
                    389,
                    390,
                    391,
                    392,
                    393,
                    394,
                    395,
                    396,
                    397,
                    398,
                    399,
                    400,
                    401,
                    402,
                    403,
                    404,
                    405,
                    406,
                    407,
                    408,
                    409,
                    410,
                    411,
                    412,
                    413,
                    414,
                    415,
                    416,
                    417,
                    418,
                    419,
                    420,
                    421,
                    422,
                    423,
                    424,
                    425,
                    426,
                    427,
                    428,
                    429,
                    430,
                    431,
                    432,
                    433,
                    434,
                    435,
                    436,
                    437,
                    438,
                    439,
                    440,
                    441,
                    442,
                    443,
                    444,
                    445,
                    446,
                    447,
                    448,
                    449,
                    450,
                    451,
                    452,
                    453,
                    454,
                    455,
                    456,
                    457,
                    458,
                    459,
                    460,
                    461,
                    462,
                    463,
                    464,
                    465,
                    466,
                    467,
                    468,
                    469,
                    470,
                    471,
                    472,
                    473,
                    474,
                    475,
                    476,
                    477,
                    478,
                    479,
                    480,
                    481,
                    482,
                    483,
                    484,
                    485,
                    486,
                    487,
                    488,
                    489,
                    490,
                    491,
                    492,
                    493,
                    494,
                    495,
                    496,
                    497,
                    498,
                    499,
                    500,
                    501,
                    502,
                    503,
                    504,
                    505,
                    506,
                    507,
                    508,
                    509,
                    510,
                    511,
                    512,
                    513,
                    514,
                    515,
                    516,
                    517,
                    518,
                    519,
                    520,
                    521,
                    522,
                    523,
                    524,
                    525,
                    526,
                    527,
                    528,
                    529,
                    530,
                    531,
                    532,
                    533,
                    534,
                    535,
                    536,
                    537,
                    538,
                    539,
                    540,
                    541,
                    542,
                    543,
                    544,
                    545,
                    546,
                    547,
                    548,
                    549,
                    550,
                    551,
                    552,
                    553,
                    554,
                    555,
                    556,
                    557,
                    558,
                    559,
                    560,
                    561,
                    562,
                    563,
                    564,
                    565,
                    566,
                    567,
                    568,
                    569,
                    570,
                    571,
                    572,
                    573,
                    574,
                    575,
                    576,
                    577,
                    578,
                    579,
                    580,
                    581,
                    582,
                    583,
                    584,
                    585,
                    586,
                    587,
                    588,
                    589,
                    590,
                    591,
                    592,
                    593,
                    594,
                    595,
                    596,
                    597,
                    598,
                    599,
                    600,
                    601,
                    602,
                    603,
                    604,
                    605,
                    606,
                    607,
                    608,
                    609,
                    610,
                    611,
                    612,
                    613,
                    614,
                    615,
                    616,
                    617,
                    618,
                    619,
                    620,
                    621,
                    622,
                    623,
                    624,
                    625,
                    626,
                    627,
                    628,
                    629,
                    630,
                    631,
                    632,
                    633,
                    634,
                    635,
                    636,
                    637,
                    638,
                    639,
                    640,
                    641,
                    642,
                    643,
                    644,
                    645,
                    646,
                    647,
                    648,
                    649,
                    650,
                    651,
                    652,
                    653,
                    654,
                    655,
                    656,
                    657,
                    658,
                    659,
                    660,
                    661,
                    662,
                    663,
                    664,
                    665,
                    666,
                    667,
                    668,
                    669,
                    670,
                    671,
                    672,
                    673,
                    674,
                    675,
                    676,
                    677,
                    678,
                    679,
                    680,
                    681,
                    682,
                    683,
                    684,
                    685,
                    686,
                    687,
                    688,
                    689,
                    690,
                    691,
                    692,
                    693,
                    694,
                    695,
                    696,
                    697,
                    698,
                    699,
                    700,
                    701,
                    702,
                    703,
                    704,
                    705,
                    706,
                    707,
                    708,
                    709,
                    710,
                    711,
                    712,
                    713,
                    714,
                    715,
                    716,
                    717,
                    718,
                    719,
                    720,
                    721,
                    722,
                    723,
                    724,
                    725,
                    726,
                    727,
                    728,
                    729,
                    730,
                    731,
                    732,
                    733,
                    734,
                    735,
                    736,
                    737,
                    738,
                    739,
                    740,
                    741,
                    742,
                    743,
                    744,
                    745,
                    746,
                    747,
                    748,
                    749,
                    750,
                    751,
                    752,
                    753,
                    754,
                    755,
                    756,
                    757,
                    758,
                    759,
                    760,
                    761,
                    762,
                    763,
                    764,
                    765,
                    766,
                    767,
                    768,
                    769,
                    770,
                    771,
                    772,
                    773,
                    774,
                    775,
                    776,
                    777,
                    778,
                    779,
                    780,
                    781,
                    782,
                    783,
                    784,
                    785,
                    786,
                    787,
                    788,
                    789,
                    790,
                    791,
                    792,
                    793,
                    794,
                    795,
                    796,
                    797,
                    798,
                    799,
                    800,
                    801,
                    802,
                    803,
                    804,
                    805,
                    806,
                    807,
                    808,
                    809,
                    810,
                    811,
                    812,
                    813,
                    814,
                    815,
                    816,
                    817,
                    818,
                    819,
                    820,
                    821,
                    822,
                    823,
                    824,
                    825,
                    826,
                    827,
                    828,
                    829,
                    830,
                    831,
                    832,
                    833,
                    834,
                    835,
                    836,
                    837,
                    838,
                    839,
                    840,
                    841,
                    842,
                    843,
                    844,
                    845,
                    846,
                    847,
                    848,
                    849,
                    850,
                    851,
                    852,
                    853,
                    854,
                    855,
                    856,
                    857,
                    858,
                    859,
                    860,
                    861,
                    862,
                    863,
                    864,
                    865,
                    866,
                    867,
                    868,
                    869,
                    870,
                    871,
                    872,
                    873,
                    874,
                    875,
                    876,
                    877,
                    878,
                    879,
                    880,
                    881,
                    882,
                    883,
                    884,
                    885,
                    886,
                    887,
                    888,
                    889,
                    890,
                    891,
                    892,
                    893,
                    894,
                    895,
                    896,
                    897,
                    898,
                    899,
                    900,
                    901,
                    902,
                    903,
                    904,
                    905,
                    906,
                    907,
                    908,
                    909,
                    910,
                    911,
                    912,
                    913,
                    914,
                    915,
                    916,
                    917,
                    918,
                    919,
                    920,
                    921,
                    922,
                    923,
                    924,
                    925,
                    926,
                    927,
                    928,
                    929,
                    930,
                    931,
                    932,
                    933,
                    934,
                    935,
                    936,
                    937,
                    938,
                    939,
                    940,
                    941,
                    942,
                    943,
                    944,
                    945,
                    946,
                    947,
                    948,
                    949,
                    950,
                    951,
                    952,
                    953,
                    954,
                    955,
                    956,
                    957,
                    958,
                    959,
                    960,
                    961,
                    962,
                    963,
                    964,
                    965,
                    966,
                    967,
                    968,
                    969,
                    970,
                    971,
                    972,
                    973,
                    974,
                    975,
                    976,
                    977,
                    978,
                    979,
                    980,
                    981,
                    982,
                    983,
                    984,
                    985,
                    986,
                    987,
                    988,
                    989,
                    990,
                    991,
                    992,
                    993,
                    994,
                    995,
                    996,
                    997,
                    998,
                    999,
                    1000
                });

            migrationBuilder.InsertData(
                schema: "Localization",
                table: "Language",
                columns: new[] { "ID", "Description", "Direction", "LanguageName" },
                values: new object[,]
                {
                    { 1, "en", "ltr", "English" },
                    { 2, "ar", "rtl", "Arabic" }
                });

            migrationBuilder.InsertData(
                schema: "Localization",
                table: "DictionaryLocalization",
                columns: new[] { "ID", "LanguageID", "Description" },
                values: new object[,]
                {
                    { 1, 1, "AYITS" },
                    { 1, 2, "AYITS" },
                    { 2, 1, "Arab Youth Innovation & Technology Summit" },
                    { 2, 2, "قمة الابتكار والتكنولوجيا للشباب العرب" },
                    { 3, 1, "Begin your journey toward an Arab future led by innovation" },
                    { 3, 2, "ابدأ رحلتك نحو مستقبل عربي تقوده الابتكار" },
                    { 4, 1, "from the Land of Civilizations… the Arab Innovation Summit Begins" },
                    { 4, 2, "من أرض الحضارات… تنطلق قمة الابتكار العربي" },
                    { 5, 1, "Hashemite Kingdom of Jordan" },
                    { 5, 2, "المملكة الأردنية الهاشمية" },
                    { 6, 1, "King Hussein Bin Talal Convention Center – Dead Sea" },
                    { 6, 2, "مركز الملك الحسين بن طلال للمؤتمرات – البحر الميت" },
                    { 7, 1, "9:00 AM – The Start of Arab Transformation" },
                    { 7, 2, "التاسعة صباحاً – انطلاقة التغيير العربي" },
                    { 8, 1, "Join the Changemakers Now" },
                    { 8, 2, "انضم إلى صُنّاع التغيير الآن" },
                    { 9, 1, "Explore Summit Details" },
                    { 9, 2, "استكشف تفاصيل القمة" },
                    { 10, 1, "Day One – (Date & Time)" },
                    { 10, 2, "اليوم الأول – (بموعد وتاريخ)" },
                    { 11, 1, "Official Opening Session with Key Dignitaries" },
                    { 11, 2, "الجلسة الافتتاحية الرسمية بمشاركة كبار الشخصيات" },
                    { 12, 1, "Opening of the Arab Smart Innovation Exhibition" },
                    { 12, 2, "افتتاح المعرض العربي للابتكار الذكي" },
                    { 13, 1, "Key Sessions on Digital Transformation and Education" },
                    { 13, 2, "جلسات محورية حول التحول الرقمي والتعليم" },
                    { 14, 1, "Explore the Day’s Agenda" },
                    { 14, 2, "استعراض أجندة اليوم" },
                    { 15, 1, "Day Two – (Date & Time)" },
                    { 15, 2, "اليوم الثاني – (بموعد وتاريخ)" },
                    { 16, 1, "Sectoral Sessions (Health, Tourism, Agriculture)" },
                    { 16, 2, "جلسات قطاعية (صحة، سياحة، زراعة)" },
                    { 17, 1, "Presentations of Promising Youth Projects" },
                    { 17, 2, "عروض لمشاريع شبابية واعدة" },
                    { 18, 1, "Specialized Discussion Forums with Thought Leaders and Executives" },
                    { 18, 2, "جلسات نقاشية متخصصة بمشاركة قادة فكر وتنفيذيين" },
                    { 19, 1, "Youth Leadership Debates" },
                    { 19, 2, "مناظرات شبابية قيادية" },
                    { 20, 1, "Arab Innovation Competitions" },
                    { 20, 2, "مسابقات الابتكار العربي" },
                    { 21, 1, "Presentation of Summit Recommendations & Future Roadmap" },
                    { 21, 2, "عرض توصيات القمة وخطة الطريق المستقبلية" },
                    { 22, 1, "About the Summit" },
                    { 22, 2, "عن القمة" },
                    { 23, 1, "Vision" },
                    { 23, 2, "الرؤية" },
                    { 24, 1, "By 2030, AYITS will stand as a pivotal turning point that redefined the role" },
                    { 24, 2, "بحلول 2030، تصبح AYITS نقطة التحول المفصلية التي أعادت تعريف دور الشباب العربي كقادة التغيير" },
                    { 25, 1, "Mission" },
                    { 25, 2, "الرسالة" },
                    { 26, 1, "To empower Arab youth to lead the region’s digital transformation through a" },
                    { 26, 2, "تمكين الشباب العربي من قيادة التحول الرقمي في المنطقة عبر مبادرة معرفية محكومة بشراكة أوسع" },
                    { 27, 1, "Objectives:" },
                    { 27, 2, "الأهداف:" },
                    { 28, 1, "AYITS 2025 aspires to turn its vision into tangible outcomes through a set" },
                    { 28, 2, "تطمح AYITS 2025 إلى تحويل رؤيتها إلى نتائج ملموسة من خلال مجموعة من المبادرات الإستراتيجية" },
                    { 29, 1, "of strategic objectives. include: • Launching cross-border Arab projects" },
                    { 29, 2, "من الأهداف الاستراتيجية، إطلاق مشاريع عربية عابرة للحدود" },
                    { 30, 1, "What is It?" },
                    { 30, 2, "ما هي؟" },
                    { 31, 1, "The Arab Youth Innovation & Technology Summit (AYITS) is a leading region" },
                    { 31, 2, "قمة الابتكار والتكنولوجيا للشباب العرب (AYITS) هي منصة إقليمية رائدة" },
                    { 32, 1, "Why?" },
                    { 32, 2, "لماذا؟" },
                    { 33, 1, "Because youth are the true engine of change in our societies. The summit is" },
                    { 33, 2, "لأن الشباب هم المحرك الفعلي للتغيير في مجتمعاتنا. القمة هي إيمان حقيقي باستثمار قدرات الشباب العربي النهائية لقيادة بل" },
                    { 34, 1, "Summit Outcomes" },
                    { 34, 2, "مخرجات القمة" },
                    { 35, 1, "AYITS is not about words or slogans — it delivers real, actionable" },
                    { 35, 2, "قمة AYITS ليست مجرد شعارات، بل منصة حقيقية تقدم نتائج ملموسة قابلة للتطبيق" },
                    { 36, 1, "outcomes that translate into policies, platforms, and initiatives." },
                    { 36, 2, "تحولها إلى سياسات ومنصات ومبادرات" },
                    { 37, 1, "Key outcomes include:" },
                    { 37, 2, "تشمل المخرجات الرئيسية:" },
                    { 38, 1, "Explore the Summit… As If You Were There!" },
                    { 38, 2, "اكتشف القمة… كما لو أنك كنت هناك!" },
                    { 39, 1, "Experience something extraordinary through our interactive 360° virtual" },
                    { 39, 2, "عش تجربة استثنائية من خلال الجولة الافتراضية التفاعلية (360 درجة)" },
                    { 40, 1, "tour. Navigate the summit venue virtually — from main halls to university" },
                    { 40, 2, "تنقل افتراضياً في موقع القمة – من القاعات الرئيسية إلى الجامعات والمكان" },
                    { 41, 1, "Explore the Interactive Summit Map" },
                    { 41, 2, "استعرض الخريطة التفاعلية للقمة" },
                    { 42, 1, "Speakers" },
                    { 42, 2, "المتحدثون" },
                    { 43, 1, "Sara Al-Omari" },
                    { 43, 2, "سارة العمري" },
                    { 44, 1, "Technical Advisor – Artificial Intelligence" },
                    { 44, 2, "مستشار تقني – الذكاء الاصطناعي" },
                    { 45, 1, "Do You Believe Change Starts with Youth?" },
                    { 45, 2, "هل تؤمن أن التغيير يبدأ مع الشباب؟" },
                    { 46, 1, "Join the summit team as a volunteer and be at the heart of the Arab world’s" },
                    { 46, 2, "انضم كمتطوع في فريق القمة، وكن في قلب حدث من أكثر الأحداث تأثيراً في الابتكار والتكنولوجيا في العالم العربي" },
                    { 47, 1, "What role do you play in our journey toward an innovative Arab future?" },
                    { 47, 2, "ما هو الدور الذي تلعبه في رحلتنا نحو مستقبل عربي مبتكر؟" },
                    { 48, 1, "Select the category that represents you so we can provide the appropriate registration form:" },
                    { 48, 2, "اختر الفئة التي تُمثلك لنتمكن من تقديم نموذج التسجيل المناسب:" },
                    { 49, 1, "Main Categories" },
                    { 49, 2, "الفئات الرئيسية" },
                    { 50, 1, "Young entrepreneurs and innovators" },
                    { 50, 2, "رياد الأعمال والمبتكرين الشباب" },
                    { 51, 1, "Founders of tech startups" },
                    { 51, 2, "مؤسسي الشركات الناشئة التقنية" },
                    { 52, 1, "University students and researchers" },
                    { 52, 2, "الطلاب الجامعيين والباحثين" },
                    { 53, 1, "Investors and funding entities" },
                    { 53, 2, "المستثمرين وجهات التمويل" },
                    { 54, 1, "Policymakers and government officials" },
                    { 54, 2, "صُناع السياسات والمسؤولين الحكوميين" },
                    { 55, 1, "Regional and international organizations" },
                    { 55, 2, "المنظمات الإقليمية والدولية" },
                    { 56, 1, "Underrepresented youth groups" },
                    { 56, 2, "الفئات الشبابية أقل حظاً" },
                    { 57, 1, "Full Name" },
                    { 57, 2, "الاسم الكامل" },
                    { 58, 1, "Email Address" },
                    { 58, 2, "البريد الإلكتروني" },
                    { 59, 1, "Phone Number" },
                    { 59, 2, "رقم الهاتف" },
                    { 60, 1, "Country / Nationality" },
                    { 60, 2, "البلد / الجنسية" },
                    { 61, 1, "Password" },
                    { 61, 2, "كلمة المرور" },
                    { 62, 1, "Age" },
                    { 62, 2, "العمر" },
                    { 63, 1, "Brief description of your idea or innovative project" },
                    { 63, 2, "نبذة مختصرة عن فكرتك أو مشروعك الابتكاري" },
                    { 64, 1, "Would you like to participate in the showcase area or innovation competition?" },
                    { 64, 2, "هل ترغب بالمشاركة في منطقة العرض أو مسابقة الابتكار؟" },
                    { 65, 1, "Startup Name" },
                    { 65, 2, "اسم الشركة الناشئة" },
                    { 66, 1, "Year of Establishment" },
                    { 66, 2, "سنة التأسيس" },
                    { 67, 1, "Website link or company profile page" },
                    { 67, 2, "رابط الموقع أو صفحة بروفايل الشركة" },
                    { 68, 1, "Are you seeking funding?" },
                    { 68, 2, "هل تبحث عن تمويل؟" },
                    { 69, 1, "University / Institute / Academy Name" },
                    { 69, 2, "اسم الجامعة / المؤسسة / الأكاديمية" },
                    { 70, 1, "Academic Major" },
                    { 70, 2, "التخصص الأكاديمي" },
                    { 71, 1, "Level of Study (Bachelor's / Master's / PhD)" },
                    { 71, 2, "درجة الدراسة (بكالوريوس / ماجستير / دكتوراه)" },
                    { 72, 1, "Do you have a graduation project or research you would like to showcase?" },
                    { 72, 2, "هل لديك مشروع تخرج أو بحث ترغب بعرضه؟" },
                    { 73, 1, "Type of Entity (Individual Investor / Investment Fund / Financing Company)" },
                    { 73, 2, "نوع الجهة (مستثمر فردي / صندوق استثماري / شركة تمويل)" },
                    { 74, 1, "Sectors of Investment Interest" },
                    { 74, 2, "القطاعات التي تهتم بالاستثمار فيها" },
                    { 75, 1, "Expected Investment Size" },
                    { 75, 2, "حجم الاستثمار المتوقع" },
                    { 76, 1, "Would you like to attend pitch sessions?" },
                    { 76, 2, "هل ترغب بحضور جلسات العرض التقديمي؟" },
                    { 77, 1, "Name of Government Entity" },
                    { 77, 2, "اسم الجهة الحكومية" },
                    { 78, 1, "Job Title" },
                    { 78, 2, "المسمى الوظيفي" },
                    { 79, 1, "Would you like to participate in a session?" },
                    { 79, 2, "هل ترغب بالمشاركة في جلسة؟" },
                    { 80, 1, "Organization Name" },
                    { 80, 2, "اسم المنظمة" },
                    { 81, 1, "Role/Title (e.g., Expert, Coordinator, Official Representative, etc.)" },
                    { 81, 2, "صفة الحضور (مثال: خبير، منسق، ممثل رسمي...إلخ)" },
                    { 82, 1, "Would you like to present an initiative or program during the summit?" },
                    { 82, 2, "هل ترغب بعرض مبادرة أو برنامج خلال القمة؟" },
                    { 83, 1, "Do you require special support to participate?" },
                    { 83, 2, "هل تحتاج إلى دعم خاص للمشاركة؟" },
                    { 84, 1, "Do you belong to a specific group (e.g., persons with disabilities, remote area residents, etc.)?" },
                    { 84, 2, "هل تنتمي إلى فئة خاصة (مثال: أشخاص ذوي إعاقة، سكان مناطق نائية...إلخ)؟" },
                    { 85, 1, "Would you like to apply for financial or logistical support program offered by the summit?" },
                    { 85, 2, "هل ترغب بالتقدم لبرنامج الدعم المالي أو اللوجستي المقدم من القمة؟" }
                });

            migrationBuilder.InsertData(
                schema: "Localization",
                table: "CompanyDictionaryLocalization",
                columns: new[] { "ID", "LanguageID", "Description", "DictionaryLocalizationID", "DictionaryLocalizationLanguageID", "TenantID" },
                values: new object[,]
                {
                    { 1, 1, "Home", null, null, 1L },
                    { 1, 2, "الصفحة الرئيسية اسامه", null, null, 1L },
                    { 2, 1, "About", null, null, 1L },
                    { 2, 2, "من نحن اسامه", null, null, 1L }
                });

            migrationBuilder.CreateIndex(
                name: "IX_CompanyDictionaryLocalization_DictionaryLocalizationID_DictionaryLocalizationLanguageID",
                schema: "Localization",
                table: "CompanyDictionaryLocalization",
                columns: new[] { "DictionaryLocalizationID", "DictionaryLocalizationLanguageID" });

            migrationBuilder.CreateIndex(
                name: "IX_CompanyDictionaryLocalization_LanguageID",
                schema: "Localization",
                table: "CompanyDictionaryLocalization",
                column: "LanguageID");

            migrationBuilder.CreateIndex(
                name: "IX_DictionaryLocalization_LanguageID",
                schema: "Localization",
                table: "DictionaryLocalization",
                column: "LanguageID");

            migrationBuilder.AddForeignKey(
                name: "FK_AspNetUsers_Language_LanguageID",
                schema: "Users",
                table: "AspNetUsers",
                column: "LanguageID",
                principalSchema: "Localization",
                principalTable: "Language",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Users_Localization_Language_LanguageID",
                schema: "Users",
                table: "Users_Localization",
                column: "LanguageID",
                principalSchema: "Localization",
                principalTable: "Language",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_AspNetUsers_Language_LanguageID",
                schema: "Users",
                table: "AspNetUsers");

            migrationBuilder.DropForeignKey(
                name: "FK_Users_Localization_Language_LanguageID",
                schema: "Users",
                table: "Users_Localization");

            migrationBuilder.DropTable(
                name: "CompanyDictionaryLocalization",
                schema: "Localization");

            migrationBuilder.DropTable(
                name: "DictionaryLocalization",
                schema: "Localization");

            migrationBuilder.DropTable(
                name: "Dictionary",
                schema: "Localization");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Language",
                schema: "Localization",
                table: "Language");

            migrationBuilder.DeleteData(
                schema: "Localization",
                table: "Language",
                keyColumn: "ID",
                keyValue: 1);

            migrationBuilder.DeleteData(
                schema: "Localization",
                table: "Language",
                keyColumn: "ID",
                keyValue: 2);

            migrationBuilder.RenameTable(
                name: "Language",
                schema: "Localization",
                newName: "Languages",
                newSchema: "Users");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Languages",
                schema: "Users",
                table: "Languages",
                column: "ID");

            migrationBuilder.AddForeignKey(
                name: "FK_AspNetUsers_Languages_LanguageID",
                schema: "Users",
                table: "AspNetUsers",
                column: "LanguageID",
                principalSchema: "Users",
                principalTable: "Languages",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Users_Localization_Languages_LanguageID",
                schema: "Users",
                table: "Users_Localization",
                column: "LanguageID",
                principalSchema: "Users",
                principalTable: "Languages",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
